version: "3.8"
services:
  medconsul-frontend-nginx:
    build:
      image: medconsul-frontend-dev
      context: ./frontend/
      dockerfile: devops/Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - medconsul-backend
  database:
    image: postgres:13
    restart: always
    container_name: database
    ports:
      - 5432:5432
    volumes:
      - ./dbfiles:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  medconsul-backend:
    build:
      image: medconsul-backend-dev
      context: ./backend/
      dockerfile: devops/Dockerfile
      target: dev
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
    ports:
      - 8080:8080
    depends_on:
      - database