version: "3.8"
services:
  medconsul-frontend-nginx:
    build:
      context: ./frontend/
      dockerfile: devops/Dockerfile
      target: app
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - medconsul-backend
  medconsul-backend:
    build:
      context: ./backend/
      dockerfile: devops/Dockerfile
      target: app
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - dbfiles:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  dbfiles:
    driver: local